//dammy data.
export const Cards = [
	{
		id: 1,
		title: 'Book Covers',
		description: 'We handle Covers For Your Book',
		img: './assets/person/3.jpg',
	},
	{
		id: 2,
		title: 'Front End Developer',
		description: 'We tackle Frontend',
		img: './assets/person/2.jpg',
	},
	{
		id: 3,
		title: 'Back End Developer',
		description: 'We tackle Backend',
		img: './assets/person/1.jpg',
	},
	{
		id: 4,
		title: 'Cloud Engineers',
		description: 'Let Us Handle your Data Troubles',
		img: './assets/person/4.jpg',
	},
	{
		id: 5,
		title: 'Graphic Design',
		description: 'Have A Logo? Talk to us',
		img: './assets/person/5.jpg',
	},
	{
		id: 6,
		title: 'Content Creators',
		description: 'We help you create creative ads',
		img: './assets/person/10.jpg',
	},
	{
		id: 7,
		title: 'Digital Marketers',
		description: 'lets reach more audience',
		img: './assets/person/7.jpg',
	},
	{
		id: 8,
		title: 'Sales Persons',
		description: 'We can sell anything',
		img: './assets/person/8.jpg',
	},
	{
		id: 9,
		title: 'PR management',
		description: 'Lets give your story',
		img: './assets/person/9.jpg',
	},
	{
		id: 10,
		title: 'Mobile Development',
		description: 'lets make that app',
		img: './assets/person/6.jpg',
	},
]

export const Projects = [
	{
		id: 1,
		img: './assets/projects/1.jpg',
		pp: './assets/dp/1.jpg',
		cat: 'Gig 1',
		username: 'Megan Glow',
	},

	{
		id: 2,
		img: './assets/projects/2.jpg',
		pp: './assets/dp/2.jpg',
		cat: 'Gig 3',
		username: 'Hannah Bird',
	},
	{
		id: 3,
		img: './assets/projects/3.jpg',
		pp: './assets/dp/3.jpg',
		cat: 'Gig 3',
		username: 'James Clark',
	},
	{
		id: 4,
		img: './assets/projects/4.jpg',
		pp: './assets/dp/4.jpg',
		cat: 'Gig 4',
		username: 'Tilda Clark',
	},
	{
		id: 5,
		img: './assets/projects/5.jpg',
		pp: './assets/dp/5.jpg',
		cat: 'Gig 5',
		username: 'Lisa Asil',
	},
	{
		id: 6,
		img: './assets/projects/6.jpg',
		pp: './assets/dp/6.jpg',
		cat: 'Gig 6',
		username: 'Emilly Clark',
	},
	{
		id: 7,
		img: './assets/projects/7.jpg',
		pp: './assets/dp/7.jpg',
		cat: 'Gig 7',
		username: 'Steve Fox',
	},
	{
		id: 8,
		img: './assets/projects/8.jpg',
		pp: './assets/dp/8.jpg',
		cat: 'Gig 8',
		username: 'John Crow',
	},
	{
		id: 9,
		img: './assets/projects/9.jpg',
		pp: './assets/dp/9.jpg',
		cat: 'Gig 9',
		username: 'Andrew Clark',
	},
	{
		id: 10,
		img: './assets/projects/10.jpg',
		pp: './assets/dp/10.jpg',
		cat: 'Gig 10',
		username: 'Patrick Ciggs',
	},
]

export const Gigss = [
	{
		id: '1',
		img: './assets/projects/1.jpg',
		pp: './assets/dp/1.jpg',
		description: 'Gig 1 Desc',
		price: 112,
		star: 5,
		username: 'Anna Bell',
	},
	{
		id: '2',
		img: './assets/projects/2.jpg',
		pp: './assets/dp/2.jpg',
		description: 'Gig 2 Desc',
		price: 234,
		star: 4,
		username: 'Alex Belling',
	},
	{
		id: '3',
		img: './assets/projects/3.jpg',
		pp: './assets/dp/3.jpg',
		description: 'Gig 3 Desc',
		price: 233,
		star: 2,
		username: 'Jeff Bullock',
	},
	{
		id: '4',
		img: './assets/projects/4.jpg',
		pp: './assets/dp/4.jpg',
		description: 'Gig 4 Desc',
		price: 665,
		star: 5,
		username: 'Beving Seller',
	},
	{
		id: '5',
		img: './assets/projects/5.jpg',
		pp: './assets/dp/5.jpg',
		description: 'Gig 5 Desc',
		price: 22,
		star: 5,
		username: 'Gregg Solo',
	},
	{
		id: '6',
		img: './assets/projects/6.jpg',
		pp: './assets/dp/6.jpg',
		description: 'Gig 6 Desc',
		price: 912,
		star: 5,
		username: 'Bling Bellout',
	},
	{
		id: '7',
		img: './assets/projects/7.jpg',
		pp: './assets/dp/7.jpg',
		description: 'Gig 7 Desc',
		price: 288,
		star: 5,
		username: 'Greg House',
	},
	{
		id: '8',
		img: './assets/projects/8.jpg',
		pp: './assets/dp/8.jpg',
		description: 'Gig 8 Desc',
		price: 883,
		star: 5,
		username: 'Bling Harlem',
	},
]
